<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Produit extends \App\Entity\Produit implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'libelle', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'descriptionCourt', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'descriptionLong', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'imagePrincipale', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'imageSecondaire1', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'imageSecondaire2', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'categories', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'ligneCommandes', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'avis'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'libelle', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'descriptionCourt', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'descriptionLong', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'imagePrincipale', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'imageSecondaire1', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'imageSecondaire2', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'categories', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'ligneCommandes', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'avis'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Produit $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelle', []);

        return parent::getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelle(string $libelle): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelle', [$libelle]);

        return parent::setLibelle($libelle);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionCourt(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionCourt', []);

        return parent::getDescriptionCourt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionCourt(string $descriptionCourt): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionCourt', [$descriptionCourt]);

        return parent::setDescriptionCourt($descriptionCourt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionLong(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionLong', []);

        return parent::getDescriptionLong();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionLong(string $descriptionLong): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionLong', [$descriptionLong]);

        return parent::setDescriptionLong($descriptionLong);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagePrincipale(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagePrincipale', []);

        return parent::getImagePrincipale();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagePrincipale(string $imagePrincipale): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagePrincipale', [$imagePrincipale]);

        return parent::setImagePrincipale($imagePrincipale);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageSecondaire1(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageSecondaire1', []);

        return parent::getImageSecondaire1();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageSecondaire1(?string $imageSecondaire1): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageSecondaire1', [$imageSecondaire1]);

        return parent::setImageSecondaire1($imageSecondaire1);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageSecondaire2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageSecondaire2', []);

        return parent::getImageSecondaire2();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageSecondaire2(?string $imageSecondaire2): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageSecondaire2', [$imageSecondaire2]);

        return parent::setImageSecondaire2($imageSecondaire2);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix(float $prix): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategories(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategories', []);

        return parent::getCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategories(array $categories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategories', [$categories]);

        return parent::setCategories($categories);
    }

    /**
     * {@inheritDoc}
     */
    public function addCategory(\App\Entity\Categorie $category): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCategory', [$category]);

        return parent::addCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCategory(\App\Entity\Categorie $category): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCategory', [$category]);

        return parent::removeCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getLigneCommandes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLigneCommandes', []);

        return parent::getLigneCommandes();
    }

    /**
     * {@inheritDoc}
     */
    public function addLigneCommande(\App\Entity\LigneCommande $ligneCommande): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLigneCommande', [$ligneCommande]);

        return parent::addLigneCommande($ligneCommande);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLigneCommande(\App\Entity\LigneCommande $ligneCommande): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLigneCommande', [$ligneCommande]);

        return parent::removeLigneCommande($ligneCommande);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvis(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvis', []);

        return parent::getAvis();
    }

    /**
     * {@inheritDoc}
     */
    public function addAvi(\App\Entity\Avis $avi): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAvi', [$avi]);

        return parent::addAvi($avi);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAvi(\App\Entity\Avis $avi): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAvi', [$avi]);

        return parent::removeAvi($avi);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
