<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.8vFVDip' shared service.

return $this->privates['.service_locator.8vFVDip'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'repoAvis' => array('privates', 'App\\Repository\\AvisRepository', 'getAvisRepositoryService.php', true),
    'repoCa' => array('privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService.php', true),
    'repoCo' => array('privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService.php', true),
    'repoL' => array('privates', 'App\\Repository\\LigneCommandeRepository', 'getLigneCommandeRepositoryService.php', true),
    'repoP' => array('privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService.php', true),
));
