<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Nu_Wv35' shared service.

return $this->privates['.service_locator.Nu_Wv35'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'prd' => array('privates', '.errored..service_locator.Nu_Wv35.App\\Entity\\Produit', NULL, 'Cannot autowire service ".service_locator.Nu_Wv35": it references class "App\\Entity\\Produit" but no such service exists.'),
));
