<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.C0vF4wV' shared service.

return $this->privates['.service_locator.C0vF4wV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'avisRepository' => array('privates', 'App\\Repository\\AvisRepository', 'getAvisRepositoryService.php', true),
));
