<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.6CKbCc3' shared service.

return $this->privates['.service_locator.6CKbCc3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'avi' => array('privates', '.errored..service_locator.6CKbCc3.App\\Entity\\Avis', NULL, 'Cannot autowire service ".service_locator.6CKbCc3": it references class "App\\Entity\\Avis" but no such service exists.'),
));
