<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.UjSjyzL' shared service.

return $this->privates['.service_locator.UjSjyzL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'repo' => array('privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService.php', true),
));
