<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'App\\Controller\\AdministrateurController::index' => array('privates', '.service_locator.8vFVDip', 'get_ServiceLocator_8vFVDipService.php', true),
    'App\\Controller\\AvisController::delete' => array('privates', '.service_locator.6CKbCc3', 'get_ServiceLocator_6CKbCc3Service.php', true),
    'App\\Controller\\AvisController::edit' => array('privates', '.service_locator.6CKbCc3', 'get_ServiceLocator_6CKbCc3Service.php', true),
    'App\\Controller\\AvisController::index' => array('privates', '.service_locator.C0vF4wV', 'get_ServiceLocator_C0vF4wVService.php', true),
    'App\\Controller\\AvisController::show' => array('privates', '.service_locator.6CKbCc3', 'get_ServiceLocator_6CKbCc3Service.php', true),
    'App\\Controller\\CartController::addOneToCart' => array('privates', '.service_locator.Nu_Wv35', 'get_ServiceLocator_NuWv35Service.php', true),
    'App\\Controller\\CartController::addToCart' => array('privates', '.service_locator.cMhnip9', 'get_ServiceLocator_CMhnip9Service.php', true),
    'App\\Controller\\CartController::cart' => array('privates', '.service_locator.ieChlwo', 'get_ServiceLocator_IeChlwoService.php', true),
    'App\\Controller\\CartController::removeOneToCart' => array('privates', '.service_locator.Nu_Wv35', 'get_ServiceLocator_NuWv35Service.php', true),
    'App\\Controller\\CategorieController::delete' => array('privates', '.service_locator.DhSqxxU', 'get_ServiceLocator_DhSqxxUService.php', true),
    'App\\Controller\\CategorieController::edit' => array('privates', '.service_locator.DhSqxxU', 'get_ServiceLocator_DhSqxxUService.php', true),
    'App\\Controller\\CategorieController::index' => array('privates', '.service_locator.pPyP_uR', 'get_ServiceLocator_PPyPURService.php', true),
    'App\\Controller\\CategorieController::show' => array('privates', '.service_locator.DhSqxxU', 'get_ServiceLocator_DhSqxxUService.php', true),
    'App\\Controller\\FrontController::categoryAction' => array('privates', '.service_locator.4HYVMOK', 'get_ServiceLocator_4HYVMOKService.php', true),
    'App\\Controller\\FrontController::index' => array('privates', '.service_locator.UjSjyzL', 'get_ServiceLocator_UjSjyzLService.php', true),
    'App\\Controller\\FrontController::libelleCategorie' => array('privates', '.service_locator.UjSjyzL', 'get_ServiceLocator_UjSjyzLService.php', true),
    'App\\Controller\\FrontController::searchBar' => array('privates', '.service_locator.ieChlwo', 'get_ServiceLocator_IeChlwoService.php', true),
    'App\\Controller\\FrontController::showProduit' => array('privates', '.service_locator.80zV_DO', 'get_ServiceLocator_80zVDOService.php', true),
    'App\\Controller\\OrderController::detailsAction' => array('privates', '.service_locator.MFsEwkP', 'get_ServiceLocator_MFsEwkPService.php', true),
    'App\\Controller\\OrderController::order' => array('privates', '.service_locator.6V0KGqG', 'get_ServiceLocator_6V0KGqGService.php', true),
    'App\\Controller\\OrderController::ordersAction' => array('privates', '.service_locator.b0jPPhg', 'get_ServiceLocator_B0jPPhgService.php', true),
    'App\\Controller\\ProduitController::delete' => array('privates', '.service_locator.cMhnip9', 'get_ServiceLocator_CMhnip9Service.php', true),
    'App\\Controller\\ProduitController::edit' => array('privates', '.service_locator.cMhnip9', 'get_ServiceLocator_CMhnip9Service.php', true),
    'App\\Controller\\ProduitController::index' => array('privates', '.service_locator.XmHQ4St', 'get_ServiceLocator_XmHQ4StService.php', true),
    'App\\Controller\\ProduitController::show' => array('privates', '.service_locator.cMhnip9', 'get_ServiceLocator_CMhnip9Service.php', true),
    'App\\Controller\\AdministrateurController:index' => array('privates', '.service_locator.8vFVDip', 'get_ServiceLocator_8vFVDipService.php', true),
    'App\\Controller\\AvisController:delete' => array('privates', '.service_locator.6CKbCc3', 'get_ServiceLocator_6CKbCc3Service.php', true),
    'App\\Controller\\AvisController:edit' => array('privates', '.service_locator.6CKbCc3', 'get_ServiceLocator_6CKbCc3Service.php', true),
    'App\\Controller\\AvisController:index' => array('privates', '.service_locator.C0vF4wV', 'get_ServiceLocator_C0vF4wVService.php', true),
    'App\\Controller\\AvisController:show' => array('privates', '.service_locator.6CKbCc3', 'get_ServiceLocator_6CKbCc3Service.php', true),
    'App\\Controller\\CartController:addOneToCart' => array('privates', '.service_locator.Nu_Wv35', 'get_ServiceLocator_NuWv35Service.php', true),
    'App\\Controller\\CartController:addToCart' => array('privates', '.service_locator.cMhnip9', 'get_ServiceLocator_CMhnip9Service.php', true),
    'App\\Controller\\CartController:cart' => array('privates', '.service_locator.ieChlwo', 'get_ServiceLocator_IeChlwoService.php', true),
    'App\\Controller\\CartController:removeOneToCart' => array('privates', '.service_locator.Nu_Wv35', 'get_ServiceLocator_NuWv35Service.php', true),
    'App\\Controller\\CategorieController:delete' => array('privates', '.service_locator.DhSqxxU', 'get_ServiceLocator_DhSqxxUService.php', true),
    'App\\Controller\\CategorieController:edit' => array('privates', '.service_locator.DhSqxxU', 'get_ServiceLocator_DhSqxxUService.php', true),
    'App\\Controller\\CategorieController:index' => array('privates', '.service_locator.pPyP_uR', 'get_ServiceLocator_PPyPURService.php', true),
    'App\\Controller\\CategorieController:show' => array('privates', '.service_locator.DhSqxxU', 'get_ServiceLocator_DhSqxxUService.php', true),
    'App\\Controller\\FrontController:categoryAction' => array('privates', '.service_locator.4HYVMOK', 'get_ServiceLocator_4HYVMOKService.php', true),
    'App\\Controller\\FrontController:index' => array('privates', '.service_locator.UjSjyzL', 'get_ServiceLocator_UjSjyzLService.php', true),
    'App\\Controller\\FrontController:libelleCategorie' => array('privates', '.service_locator.UjSjyzL', 'get_ServiceLocator_UjSjyzLService.php', true),
    'App\\Controller\\FrontController:searchBar' => array('privates', '.service_locator.ieChlwo', 'get_ServiceLocator_IeChlwoService.php', true),
    'App\\Controller\\FrontController:showProduit' => array('privates', '.service_locator.80zV_DO', 'get_ServiceLocator_80zVDOService.php', true),
    'App\\Controller\\OrderController:detailsAction' => array('privates', '.service_locator.MFsEwkP', 'get_ServiceLocator_MFsEwkPService.php', true),
    'App\\Controller\\OrderController:order' => array('privates', '.service_locator.6V0KGqG', 'get_ServiceLocator_6V0KGqGService.php', true),
    'App\\Controller\\OrderController:ordersAction' => array('privates', '.service_locator.b0jPPhg', 'get_ServiceLocator_B0jPPhgService.php', true),
    'App\\Controller\\ProduitController:delete' => array('privates', '.service_locator.cMhnip9', 'get_ServiceLocator_CMhnip9Service.php', true),
    'App\\Controller\\ProduitController:edit' => array('privates', '.service_locator.cMhnip9', 'get_ServiceLocator_CMhnip9Service.php', true),
    'App\\Controller\\ProduitController:index' => array('privates', '.service_locator.XmHQ4St', 'get_ServiceLocator_XmHQ4StService.php', true),
    'App\\Controller\\ProduitController:show' => array('privates', '.service_locator.cMhnip9', 'get_ServiceLocator_CMhnip9Service.php', true),
))), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
