<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPuyTSkq\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPuyTSkq/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPuyTSkq.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPuyTSkq\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPuyTSkq\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'PuyTSkq',
    'container.build_id' => '12e1ec53',
    'container.build_time' => 1546271062,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPuyTSkq');
